config/routes.rb
# frozen_string_literal: true

require 'api/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  resource :profile, only: [:show, :update] do
    member do
      put :reset_private_token
    end
  end

  resources :hosts, only: [:show, :update]
  resources :current_host_stats, only: :index
  resources :usage_data, only: [:new, :create, :show] do
    collection do
      get 'months'
      post 'schedule_backfill'
    end
  end

  resources :version_checks, only: [:index, :show]
  resources :metrics, only: [:index, :show], constraints: { id: /[A-Za-z_0-9]+/ }
  resources :versions, except: :show
  resources :usage_ping_errors, only: [:create]
  resources :usage_ping_metadata, only: [:create]

  get 'check(.:format)',
      to: 'version_checks#check',
      defaults: { format: 'png' },
      constraints: { format: /png|svg|json/ }

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'versions#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end
end

app/models/version_check.rb
# frozen_string_literal: true

class VersionCheck < ApplicationRecord
  belongs_to :host, optional: true, touch: true

  validates :gitlab_version, presence: true

  scope :with_host, -> { includes(:host) }
  scope :ordered_by_id_with_limit, ->(rows) { recent_first.limit(rows) }
  scope :uniq_gitlab_versions, -> { pluck(:gitlab_version).uniq.reject(&:blank?) }
  scope :recent_first, -> { order(id: :desc) }

  def self.search(term)
    where('LOWER(referer_url) LIKE ?', "%#{sanitize_sql_like(term.downcase)}%") # rubocop:disable GitlabSecurity/SqlInjection
  end

  def up_to_date?
    Version.latest?(general_gitlab_version)
  end

  def update_required?
    Version.where(version: general_gitlab_version)
      .where.not(vulnerability_type: Version.vulnerability_types[:not_vulnerable]).any?
  end

  def critical_vulnerability?
    Version.where(version: general_gitlab_version)
      .where(vulnerability_type: Version.vulnerability_types[:critical]).any?
  end

  def general_gitlab_version
    gitlab_version.sub(/-ee\Z/, '')
  end
end

app/controllers/version_checks_controller.rb
# frozen_string_literal: true

class VersionChecksController < ApplicationController
  LAST_VERSIONS_SHOWN_COUNT = 3

  skip_before_action :authenticate_user!, only: :check

  def index
    @version_checks = VersionCheck.with_host.recent_first
    @version_checks = @version_checks.search(params[:search]) if params[:search].present?
    @version_checks = @version_checks.page(params[:page]).without_count
  end

  def show
    @version_check = VersionCheck.find(params[:id])
  end

  def check
    return head(404) unless request.env['HTTP_REFERER'].present?

    begin
      service = VersionCheckCreatorService.new(params[:gitlab_info], request)
      version_check_result = service.execute
    rescue ArgumentError
      return head(404)
    end

    respond_to do |format|
      format.png do
        send_file File.realpath("public/update_#{version_check_result[:status]}.png"),
                  type: 'image/png', disposition: 'inline'
      end

      format.svg do
        send_file File.realpath("public/update_#{version_check_result[:status]}.svg"),
                  type: 'image/svg+xml', disposition: 'inline'
      end

      format.json do
        if version_check_result[:status] == 'failed'
          render json: {}, status: :bad_request
        else
          latest_version = Version.latest
          render json: {
            latest_stable_versions: latest_stable_versions,
            latest_version: latest_version.version,
            severity: version_check_result[:status],
            critical_vulnerability: version_check_result[:critical_vulnerability],
            details: latest_version.details
          }
        end
      end
    end
  end

  private

  def latest_stable_versions
    Version.latest_minor_releases_after(
      count: LAST_VERSIONS_SHOWN_COUNT,
      after_version: GitlabInfoDecoder.decode(params[:gitlab_info])['version']
    ).map(&:version)
  end
end

app/helpers/version_checks_helper.rb
# frozen_string_literal: true

module VersionChecksHelper
  def headers(request_data)
    JSON.parse(request_data)
  end

  # host_url is a route
  def host_url_for_display(host)
    host&.url || '-'
  end
end

app/views/version_checks/index.html.haml
%h2.pb-2
  Version Checks
  .float-right
    = form_for version_checks_path, method: :get, html: { class: 'form-inline' } do
      .input-group
        = search_field_tag :search, params[:search], class: 'form-control'
        .input-group-append
          = button_tag 'Search', class: 'btn btn-secondary'

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Application URL
      %th GitLab Version
      %th Created

  %tbody
    - @version_checks.each do |version_check|
      %tr
        %td
          = link_to version_check_path(version_check) do
            \##{version_check.id}
        %td= host_url_for_display(version_check.host)
        %td= version_check.gitlab_version
        %td= version_check.created_at.to_s

%hr
= render 'shared/pagination_without_count', collection: @version_checks

app/views/version_checks/show.html.haml
%h3 Version check ##{@version_check.id}

.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th Header
        %th Value
    %tbody
      %tr
        %td GitLab URL
        %td
          - if @version_check.host
            = link_to host_path(@version_check.host) do
              %strong= host_url_for_display(@version_check.host)
          - else
            %strong= host_url_for_display(@version_check.host)
      %tr
        %td GitLab version
        %td
          %strong= @version_check.gitlab_version
      %tr
        %td Request sent
        %td= @version_check.created_at.to_s
      - headers(@version_check.request_data).each do |header, value|
        %tr
          %td= header
          %td= value

= link_to 'Back', version_checks_path, class: 'btn btn-secondary'